# Generated by Django 5.2.8 on 2025-11-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='Name to identify the page (e.g. Home, About, Services)', max_length=200, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('twitter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_description', models.TextField(blank=True, null=True)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('schema_json', models.TextField(blank=True, help_text='Paste full JSON-LD schema here', null=True)),
                ('extra_header', models.TextField(blank=True, help_text='Add extra scripts (analytics, pixels…)', null=True)),
            ],
        ),
    ]
