# Generated by Django 5.2.8 on 2025-12-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='og_type',
            field=models.CharField(blank=True, default='website', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='robots',
            field=models.CharField(blank=True, default='index, follow', help_text='e.g., index, follow or noindex, nofollow', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='twitter_card',
            field=models.CharField(blank=True, default='summary_large_image', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Recommended: 150-160 characters', null=True),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Recommended: 50-60 characters', max_length=255, null=True),
        ),
    ]
