# Generated by Django 5.2.8 on 2025-12-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_blogpost_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_from', models.CharField(max_length=255)),
                ('location_to', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('botcheck', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
