# Generated by Django 5.2.8 on 2025-12-15 16:44

import booking.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='team_photos/', validators=[booking.utils.validate_team_photo]),
        ),
    ]
